# Generated by Django 5.2.5 on 2025-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
