# Generated by Django 5.2.5 on 2025-09-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
